version: '2'

services:
  catalog:
    build: ../../../catalog/
    container_name: catalog
    environment:
      - PORT=3010
    ports: ["3010:3010"]

  inventory:
    build: ../../../inventory/
    container_name: inventory
    environment:
      - PORT=3020
    ports: ["3020:3020"]

  api:
    build: ../../../api-gateway/
    container_name: api
    environment:
      - PORT=3000
      - CATALOGADDR=catalog:3010
      - INVENTORYADDR=inventory:3020
    ports: ["3000:3000"]
    depends_on:
      - catalog
      - inventory
